// vue/src/App.vue
<template>
  <div class="containerVue">
    <Header  />
    <AboutMe />
    <Education />
    <Experience />
    <Projects />
    
  </div>
</template>

<script>
import Header from './components/Header';
import AboutMe from './components/AboutMe/AboutMe.vue';
import Experience from './components/Experience/Experience.vue';
import Projects from './components/Projects/Projects.vue';
import Education from './components/Education/Education.vue';



export default {
  name: "App",
  components: {
    Header,
    AboutMe,
    Experience,
    Projects,
    Education,
    
  }
};
</script>

<style scoped>

</style>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  
})
export class AppComponent {
  title: string = 'Angular site';
}

<div >
    <app-header></app-header>
    <app-aboutme></app-aboutme>
    <app-education></app-education>
    <app-experience></app-experience>
    <app-projects></app-projects>
</div>
