// angular/src/app/components/aboutme/aboutme.component.ts
import { Component, OnInit } from '@angular/core';
import { AboutmeDataService } from 'src/app/services/aboutme-data.service';
import { AboutMeData } from './AboutMeData';

@Component({
  selector: 'app-aboutme',
  templateUrl: './aboutme.component.html',
  styleUrls: ['./aboutme.component.css']
})
export class AboutmeComponent implements OnInit {
  alldata: AboutMeData[] = [];

  constructor(private aboutmeDataService: AboutmeDataService) { }

  ngOnInit(): void {
    this.aboutmeDataService.getData().subscribe((alldata) => (this.alldata = alldata));
  }

}

<section id="about" class="aboutMe">
    <div class='wrapper'>
        <div class='headerTextAbout'>
            <div class='line'></div>
            <h1 class='text'>ABOUT ME</h1>
            <div class='line'></div>
        </div>
        <div class='sectionContent'>
            <app-aboutme-item *ngFor="let data of alldata" [data]="data"></app-aboutme-item>
        </div>
    </div>
</section>

// react/src/components/About/AboutMe.jsx
import React  from 'react'
import { useState, useEffect } from 'react'
import AllData from './AllData'
import './about.css'


const AboutMe = () => {
    const [alldata, setAllData] = useState([])    

    useEffect(() => {
        const geAlltData = async () => {
          const dataFromServer = await fetchAboutData()
          setAllData(dataFromServer)
          
        }
        
        geAlltData()
      }, [])

    const fetchAboutData = async () => {
        const res = await fetch('http://localhost:5001/aboutmeData')
        const data = await res.json()
        
        return(data)
    }
    console.log(alldata)


    return (
        <section id="about" className="aboutMe">
            <div className='wrapper'>
                <div className='headerTextAbout'>
                    <div className='line'></div>
                    <h1 className='text'>ABOUT ME</h1>
                    <div className='line'></div>
                </div>
                <div className='sectionContent'>
                    <AllData alldata={alldata} />
                </div>
            </div>
        </section>
    )

}

export default AboutMe
